### ISSUE TITLE
Implement i18next for commands

### ISSUE THREAD

**Issue by RalphORama** [podaboutlist/linkfix-for-discord#10]
If we are going to add more slash commands for v2, we should preemptively implement [i18next](https://www.i18next.com/overview/getting-started), especially since some language strings are already [quite long](https://github.com/podaboutlist/linkfix-for-discord/blob/main/src/commands/Help.ts#L11).

**Comment by shoegaze** [comment]
https://github.com/podaboutlist/linkfix-for-discord/pull/87
