### ISSUE TITLE
Publish Arm Docker Images in Actions

### ISSUE THREAD

**Issue by Fummowo** [podaboutlist/linkfix-for-discord#103]
Could we get Arm Docker Images published aswell please?
Should just be `platforms: linux/amd64,linux/arm64` added in here if i'm not mistaken:
https://github.com/podaboutlist/linkfix-for-discord/blob/bcbb8a1ba3499504bfc9f633c774a6073eac64ae/.github/workflows/_build.yml#L21-L27

I use an arm vps so this just makes it a lil easier, but i'm sure i'm not the only one :))

**Comment by RalphORama** [comment]
Let me know if that works!
