### ISSUE TITLE
[Feature Request] Bluesky with bskyx.app

### ISSUE THREAD

**Issue by real-jame** [podaboutlist/linkfix-for-discord#142]
Bluesky video links don't embed on Discord, but they do with the Bluesky fixer: https://github.com/Rapougnac/VixBluesky
![image](https://github.com/user-attachments/assets/bc6b40cd-7bbe-4b45-9a37-fdb5825421a6)

**Comment by RalphORama** [comment]
This is available in production now! Feel free to open a new issue if you run into any problems with it.

**Comment by real-jame** [comment]
Thank you so much!!
