### ISSUE TITLE
Get a real logging framework

### ISSUE THREAD

**Issue by RalphORama** [podaboutlist/linkfix-for-discord#22]
I am writing so many freaking `console.debug()` statements its crazy. We should implement a structured logging framework.

I don't want to deal with JSON output (even though that may end up being an unwise decision). And timestamps shouldn't be a huge issue since `docker [compose] logs` has an option to show timestamps.

Some options from a quick "DuckDuckGo" web search:

  - [winston](https://github.com/winstonjs/winston)
     - docs seem more fleshed out than log4js-node
     - updated most recently
  - [log4js-node](https://github.com/log4js-node/log4js-node)
     - explicit mentions of typescript in the readme
     - I'm familar with log4j output from my years of running Minecraft servers 🙂

**Comment by shoegaze** [comment]
Might be useful down the line to add a environment flag (`NODE_ENV = 'development' | 'production'`) to `.env`, so we can filter out logs depending on the environment. Seems easy to add afterward, though.

**Comment by shoegaze** [comment]
See: https://github.com/shoegaze/linkfix-for-discord/tree/22-add-logging (No PR yet, waiting for #10 to merge)
