### ISSUE TITLE
Issue with index.ts

### ISSUE THREAD

**Issue by Joolian1** [podaboutlist/linkfix-for-discord#42]
![image](https://github.com/podaboutlist/linkfix-for-discord/assets/73612835/63908237-88cf-4f81-93fa-982baf8e5026)
Hi There i have a server and i want to host it on my server but i got an issues i got an issue before this one but the i found the solution in stackoverflow but now i faced a new one ..

Using Node.js v18 .

**Comment by RalphORama** [comment]
you have to compile the typescript to javascript. use these two commands:

1. `npm run build`
2. `npm start`

**Comment by Joolian1** [comment]
Still same issue, which is weird i got like 2~3 servers with my bots and they are fine, except this one and i'm ngl Yours is so impressive !

**Comment by Joolian1** [comment]
![image](https://github.com/podaboutlist/linkfix-for-discord/assets/73612835/8971c081-1238-4b31-a223-55f62185f5ec)
i tried to change the packages dw same .

**Comment by RalphORama** [comment]
you still have the startup file set to `src/index.ts`> you need to change it to `dist/index.js`

**Comment by Joolian1** [comment]
![image](https://github.com/podaboutlist/linkfix-for-discord/assets/73612835/4218b2bf-6aba-4208-a261-5b60db910648)
![image](https://github.com/podaboutlist/linkfix-for-discord/assets/73612835/175de3f6-a3a9-43e7-b12d-c8722d4c41cd)

**Comment by RalphORama** [comment]
quite frankly I have no clue what server management software you're using and it's outside the scope of this project to support it. 

if you're unable to follow the 3 steps I provided earlier it would probably be easier for you to invite the bot to your server using the invite link on the main page of this repository.
