### ISSUE TITLE
The Host said This:

### ISSUE THREAD

**Issue by Joolian1** [podaboutlist/linkfix-for-discord#44]
Hello the support of the host said this ( They even tried to run it few times ) 
![image](https://github.com/podaboutlist/linkfix-for-discord/assets/73612835/043afc58-4f73-41bf-a6b5-e1c994e15926)
![image_2](https://github.com/podaboutlist/linkfix-for-discord/assets/73612835/d49d6ca5-3c2c-4b5a-8673-70cb8eec678e)

You said do not open another issue abt this but i did what the support said because they believe the issue from your code . 

Let me know so i can send a screenshot in that ticket

**Comment by Joolian1** [comment]
Thank you .

**Comment by RalphORama** [comment]
![image](https://github.com/podaboutlist/linkfix-for-discord/assets/6566104/fcee1bde-e678-4d62-aa7a-e9f7ee434728)

It is not an error with the code. It properly compiles and runs both on my local machine and on the server I am hosting the main LinkFix bot on.

Like I said previously, if the `npm install`/`npm run build`/`npm start` steps are executed in order, the code will transpile and the bot will run. I do not know what hosting platform you are using or how it handles these steps. That is something you and your host have to figure out. 

If your host supports Docker containers, which appears to be the case, you can pull a pre-built image from `ghcr.io/podaboutlist/linkfix:latest`.

In either case, you will need to configure the `DISCORD_BOT_TOKEN` environment variable.
