### ISSUE TITLE
Bot doesn't function once installed

### ISSUE THREAD

**Issue by lameyer** [podaboutlist/linkfix-for-discord#49]
I've installed the bot on my Discord server, and it just doesn't seem to do anything. The slash commands work, but it doesn't embed any links. Do I need to enable it in some way that I'm not seeing? I've had luck with other similar bots, just not yours.

Thanks for your help!

**Comment by RalphORama** [comment]
Hi, sorry you're having the issue. It appears to work in my test server. It should automatically reply whenever someone posts a twitter link, etc.

Could you please check that:

- The bot has permission to read and send messages
- The bot has access to the channel you're posting links in

**Comment by lameyer** [comment]
Yes, I have this issue when testing it in a private channel I've manually added it to (as well as all other channels), and I've granted it all the permissions it asked for. Here's some screenshots of the menus:
https://imgur.com/a/F4SygD3

let me know if there's any other info I can send to you

**Comment by RalphORama** [comment]
could you please post a screenshot of the permissions granted to the LinkFix role in that channel?

**Comment by lameyer** [comment]
All the Advanced Permissions are set to the default (except for View Channel)
https://imgur.com/a/BUoEKgV

**Comment by RalphORama** [comment]
Try setting "send messages" to ✅ and see if that fixes the issue. 

I haven't encountered this with other servers so it may take some tinkering to fix. Thanks for your patience.

**Comment by lameyer** [comment]
No problem, thank you for looking into this 🙏 

When I switch Send Messages (or any of the other permissions already allowed for the bot) to ✅ , it just switches back to `/` when I click Save Changes. I believe this is because `/` is giving it the inherited value, which is already enabled.

**Comment by RalphORama** [comment]
I haven't seen that behavior before. Could you check your server's audit log to see if something else is resetting the permissions?

**Comment by lameyer** [comment]
I'm not seeing anything unusual in the audit log (I removed and re-added with full permissions to make sure I could see anything going on)

![Screenshot 2024-01-26 at 11 35 32 AM](https://github.com/podaboutlist/linkfix-for-discord/assets/8021670/0c10ec78-ca9b-47de-97e1-1073e0e5689f)
