### ISSUE TITLE
IOS embed failures

### ISSUE THREAD

**Issue by fish-el** [podaboutlist/linkfix-for-discord#98]
Members of my server who use iphones have reported that the embedded video does not play, and just shows the loading symbol eternally. Videos play fine on various android OS and on PC. discord app updates and OS updates were attempted and did not fix the issue.

**Comment by RalphORama** [comment]
Hi, thanks for reporting. This is probably an issue with iOS/the Discord app for iOS. You could also try reporting to [FixTwitter](https://github.com/FixTweet/FxTwitter), which is what LinkFix uses. Unfortunately it's not something we can fix on our end.
